name: Building and running test using Self Hosted runner and github

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant dist
  test:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Running JUnit Tests & Generating reports
        run: ant test-reports
  
  docs:
    runs-on: self-hosted
    steps:
      - name: Generating documentation
        run: ant javadoc